name: TerraLayers
version: ${project.version}
main: org.btuk.terralayers.plugin.TerraLayersPlugin
api-version: '1.21'
load: STARTUP

dependencies:
  server:
    Multiverse-Core:
      load: BEFORE
      required: true
